### ISSUE TITLE
'NODE_ENV' is not recognized as an internal or external command, operable program or batch file

### ISSUE THREAD

**Issue by oshihirii** [square/connect-api-examples#283]
Windows 10  
Node v14.18.1  

I've cloned connect-api-examples with:

    gh repo clone square/connect-api-examples

I'm following the instructions here: for `connect-examples/v2/node_subscription`:  

https://github.com/square/connect-api-examples/tree/master/connect-examples/v2/node_subscription

I'm in the following location:

    /connect-api-examples/connect-examples/v2/node_subscription

I've created a `.env` file with this content:

    SQUARE_ACCESS_TOKEN=token-is-here  

and run:

    npm install

and get error:  
```
$ npm test

> square-subscription-api-sample-app@1.0.0 test D:\REPOS\connect-api-examples\connect-examples\v2\node_subscription
> NODE_ENV=sandbox nodemon -e js,pug ./bin/www

'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Test failed.  See above for more details.
```

Perhaps it has something to do with issues discussed here?

https://stackoverflow.com/q/11928013

**Comment by oshihirii** [comment]
Update:

I don't know if this is the correct thing to do or not.

In `package.json` I added `SET ` before `NODE_ENV` and `&&` after the environment setting.

I.e. I replaced this:  
```
  "scripts": {
    "start": "NODE_ENV=production nodemon -e js,pug ./bin/www",
    "test": "NODE_ENV=sandbox nodemon -e js,pug ./bin/www",
    "seed": "NODE_ENV=sandbox node ./bin/script/seed-data.js generate",
    "clear": "NODE_ENV=sandbox node ./bin/script/seed-data.js clear",
    "help": "NODE_ENV=sandbox node ./bin/script/seed-data.js --help"
  }
```  
with this:  
```
  "scripts": {
    "start": "SET NODE_ENV=production&& nodemon -e js,pug ./bin/www",
    "test": "SET NODE_ENV=sandbox&& nodemon -e js,pug ./bin/www",
    "seed": "SET NODE_ENV=sandbox&& node ./bin/script/seed-data.js generate",
    "clear": "SET NODE_ENV=sandbox&& node ./bin/script/seed-data.js clear",
    "help": "SET NODE_ENV=sandbox&& node ./bin/script/seed-data.js --help"
  }
```  
And nodemon starts:
```
[nodemon] 2.0.7
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,pug
[nodemon] starting `node ./bin/www`
Listening on http://localhost:3000
```
When I go to page in browser, I get error:
```
No valid customer retreived, this example only works with customers that have email information.
Error: No valid customer retreived, this example only works with customers that have email information.
    at D:\REPOS\connect-api-examples\connect-examples\v2\node_subscription\routes\index.js:56:13
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by emmac3** [comment]
Hi @oshihirii,

This is a known issue that has been reported before but we are unable to reproduce it on our end. I'd like to investigate further. Would you kindly provide me with the terminal that you are running these commands in?

**Comment by oshihirii** [comment]
i am using Windows Terminal (Preview) and Git Bash is my default profile (from Git).  

may I ask which issue you are referring to?  

this issue started with the NODE_ENV issue, but then there were two other issues described:  1)  the app doesn’t load  2) npm run seed doesn’t work.

**Comment by oshihirii** [comment]
Update:

If I manually add clients to the sandbox environment, then the app loads when running:
```
npm test
```
![gym_members_app_loads](https://user-images.githubusercontent.com/5090307/142795566-3cfba3e8-942a-468f-a6f4-9969d08cc93c.png)

However, when I click on one of the customer names, I get:

![gym_members_app_loads_error](https://user-images.githubusercontent.com/5090307/142795740-2fb8f3bd-7b95-4ec1-a7ba-c47c0aab204e.png)

Error message in chrome dev tools is:

    GET http://localhost:3000/management/some-code-here/some-code-here 500 (Internal Server Error)

**Comment by kharithomas** [comment]
This is a very old thread, but I had this issue when starting. 

Simple solution is to remove the `test` script inside `package.json` and pass the `NODE_ENV` as a param to the `env.json` file instead like this:

**package.json:**
```
"scripts": {
    "start": "nodemon -e js,pug ./bin/www",
    "test": "echo 'No tests found'",
    "seed": "node ./bin/script/seed-catalog.js generate",
    "clear": "node ./bin/script/seed-catalog.js clear",
    "help": "node ./bin/script/seed-catalog.js --help"
  },
``` 

**env.json:**
```
NODE_ENV=sandbox # or use 'production' here instead
SQ_APPLICATION_ID=your-application-id
SQ_ACCESS_TOKEN=your-access-token
```
