### ISSUE TITLE
Order-Ahead Sample install

### ISSUE THREAD

**Issue by taterbluejack** [square/connect-api-examples#396]
Hi, when I enter 'npm install', I get these error messages below. How do I fix? Please let me know what other information you need to understand this issue.

npm ERR! code ECONNREFUSED
npm ERR! syscall connect
npm ERR! errno ECONNREFUSED
npm ERR! FetchError: request to https://artifactory.global.square/artifactory/api/npm/square-npm/to-regex-range/-/to-regex-range-5.0.1.tgz failed, reason: connect ECONNREFUSED 127.0.0.1:3000
npm ERR!     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/minipass-fetch/lib/index.js:130:14)
npm ERR!     at ClientRequest.emit (node:events:513:28)
npm ERR!     at onerror (/usr/local/lib/node_modules/npm/node_modules/agent-base/dist/src/index.js:117:21)
npm ERR!     at callbackError (/usr/local/lib/node_modules/npm/node_modules/agent-base/dist/src/index.js:136:17)
npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
npm ERR!  FetchError: request to https://artifactory.global.square/artifactory/api/npm/square-npm/to-regex-range/-/to-regex-range-5.0.1.tgz failed, reason: connect ECONNREFUSED 127.0.0.1:3000
npm ERR!     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/minipass-fetch/lib/index.js:130:14)
npm ERR!     at ClientRequest.emit (node:events:513:28)
npm ERR!     at onerror (/usr/local/lib/node_modules/npm/node_modules/agent-base/dist/src/index.js:117:21)
npm ERR!     at callbackError (/usr/local/lib/node_modules/npm/node_modules/agent-base/dist/src/index.js:136:17)
npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
npm ERR!   code: 'ECONNREFUSED',
npm ERR!   errno: 'ECONNREFUSED',
npm ERR!   syscall: 'connect',
npm ERR!   address: '127.0.0.1',
npm ERR!   port: 3000,
npm ERR!   type: 'system'
npm ERR! }
npm ERR! 
npm ERR! If you are behind a proxy, please make sure that the
npm ERR! 'proxy' config is set properly.  See: 'npm help config'

**Comment by mglombicki-square** [comment]
Thanks for reporting, this looks like a misconfiguration in our package lock files. We will push a fix soon.

**Comment by ybtag** [comment]
There is no address artifactory.global.square
