### ISSUE TITLE
`npm install` ENOTFOUND:  artifactory.global.square

### ISSUE THREAD

**Issue by lee0c** [square/connect-api-examples#471]
Hi. I am trying to run the [graphql sample](https://github.com/square/connect-api-examples/tree/master/connect-examples/v2/graphql-sample-app). When I attempt npm install, I get the following:

```sh
npm error code ENOTFOUND
npm error syscall getaddrinfo
npm error errno ENOTFOUND
npm error network request to https://artifactory.global.square/artifactory/api/npm/square-npm/word-wrap/-/word-wrap-1.2.5.tgz failed, reason: getaddrinfo ENOTFOUND artifactory.global.square
npm error network This is a problem related to network connectivity.
npm error network In most cases you are behind a proxy or have bad network settings.
npm error network
npm error network If you are behind a proxy, please make sure that the
npm error network 'proxy' config is set properly.  See: 'npm help config'
```

I'm not behind a proxy, just on my home network which as far as I know has extremely boring configuration.

I've tried these commands as well:
```sh
python3 -c "import socket; print(socket.getaddrinfo('artifactory.global.square', 443))"
# output
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
```

```sh
ping artifactory.global.square
# output
ping: artifactory.global.square: Name or service not known
```

```sh
curl https://artifactory.global.square/artifactory/api/npm/square-npm/word-wrap/-/word-wrap-1.2.5.tgz
# output
curl: (6) Could not resolve host: artifactory.global.square
```

Any idea what I am doing wrong?

**Comment by bai312** [comment]
我安装ios-deploy 时也报了这写错误，我也想知道怎么解决这类问题
